version: '2'
services:
  node1:
    environment:
      - SPORT=8001
      - BWTN=2048
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8001:8001"
  node2:
    environment:
      - SPORT=8002
      - BWTN=2048
      - PEERS=ws://node1:8001-983
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8002:8002"
    links:
      - node1:node1
  node3:
    environment:
      - SPORT=8003
      - BWTN=2048
      - PEERS=ws://node1:8001-899,ws://node2:8002-1620
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    links:
      - node1:node1
      - node2:node2
  node4:
    environment:
      - SPORT=8004
      - BWTN=2048
      - PEERS=ws://node1:8001-925,ws://node2:8002-1489,ws://node3:8003-2020
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
  node5:
    environment:
      - SPORT=8005
      - BWTN=2048
      - PEERS=ws://node1:8001-1505,ws://node2:8002-1256,ws://node3:8003-1656,ws://node4:8004-1725
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
  node6:
    environment:
      - SPORT=8006
      - BWTN=2048
      - PEERS=ws://node1:8001-1252,ws://node2:8002-1502,ws://node3:8003-2071,ws://node4:8004-2438
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
      - node5:node5
  node7:
    environment:
      - SPORT=8007
      - BWTN=2048
      - PEERS=ws://node1:8001-1870,ws://node2:8002-1801,ws://node3:8003-2289,ws://node4:8004-2605,ws://node5:8005-2572
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
      - node5:node5
      - node6:node6
  node8:
    environment:
      - SPORT=8008
      - BWTN=2048
      - PEERS=ws://node1:8001-2137,ws://node3:8003-2289,ws://node4:8004-2838,ws://node5:8005-2452,ws://node6:8006-2656,ws://node7:8007-3504
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
      - node5:node5
      - node6:node6
      - node7:node7
  node9:
    environment:
      - SPORT=8009
      - BWTN=2048
      - PEERS=ws://node1:8001-2171,ws://node2:8002-2669,ws://node3:8003-2457,ws://node4:8004-2502,ws://node5:8005-3108,ws://node8:8008-3671
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
      - node5:node5
      - node6:node6
      - node7:node7
      - node8:node8
  node10:
    environment:
      - SPORT=8010
      - BWTN=2048
      - PEERS=ws://node1:8001-2508,ws://node2:8002-2626,ws://node3:8003-2656,ws://node4:8004-2680,ws://node5:8005-3521,ws://node6:8006-3583,ws://node7:8007-3499,ws://node8:8008-3502,ws://node9:8009-3936
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    links:
      - node1:node1
      - node2:node2
      - node3:node3
      - node4:node4
      - node5:node5
      - node6:node6
      - node7:node7
      - node8:node8
      - node9:node9